import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createProblem, deleteProblem, fetchProblem, fetchProblems, updateProblem, validateProblem, type TsumeProblem, type TsumeProblemInput } from "../api/client";
import EditorBoard from "../components/EditorBoard";
import SolutionRecorder from "../components/SolutionRecorder";
import { emptyPosition, parseMoveList, parseSfen, toSfen, validateUsiMoves, type EditorPosition } from "../shogi/editor";

const blank: TsumeProblemInput = { title:"", initial_sfen:"9/9/9/9/9/9/9/9/9 b - 1", mate_length:1, difficulty:1, tags:[], solution_moves:[], opponent_moves:[], explanation:"", is_favorite:false };
export default function ProblemEditorPage() {
  const { id } = useParams(); const nav = useNavigate(); const editingId = id ? Number(id) : null;
  const [problems,setProblems]=useState<TsumeProblem[]>([]); const [form,setForm]=useState<TsumeProblemInput>(blank); const [pos,setPos]=useState<EditorPosition>(()=>emptyPosition());
  const [solutionText,setSolutionText]=useState(""); const [opponentText,setOpponentText]=useState(""); const [tagsText,setTagsText]=useState(""); const [messages,setMessages]=useState<string[]>([]); const [info,setInfo]=useState<string|null>(null);
  const [recorderSeed, setRecorderSeed] = useState(0);
  useEffect(()=>{ fetchProblems().then(setProblems).catch(e=>setMessages([`問題一覧の取得に失敗しました: ${e}`])); },[]);
  useEffect(()=>{
    // URLの編集対象変更時にフォームへ反映する。
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if(!editingId){ setForm(blank); setPos(parseSfen(blank.initial_sfen)); setSolutionText(""); setOpponentText(""); setTagsText(""); setRecorderSeed((x) => x + 1); return; } fetchProblem(editingId).then(p=>{ setForm({...p, is_favorite:p.is_favorite}); setPos(parseSfen(p.initial_sfen)); setSolutionText(p.solution_moves.join("\n")); setOpponentText(p.opponent_moves.join("\n")); setTagsText(p.tags.join(", ")); setRecorderSeed((x) => x + 1); }).catch(e=>setMessages([`問題の取得に失敗しました: ${e}`])); },[editingId]);
  const sfen = useMemo(()=>toSfen(pos),[pos]);
  const recorderInitial = useMemo(() => { try { return parseSfen(form.initial_sfen || sfen); } catch { return pos; } }, [form.initial_sfen, pos, sfen]);
  function syncSfen(next: EditorPosition){ setPos(next); setForm(f=>({...f, initial_sfen: toSfen(next)})); }
  function applySfen(){ try { const p=parseSfen(form.initial_sfen); setPos(p); setRecorderSeed((x) => x + 1); setMessages([]); } catch(e){ setMessages([`SFENが不正です: ${e instanceof Error ? e.message : e}`]); } }
  async function runValidation(body: TsumeProblemInput){ const local:string[]=[]; try{ parseSfen(body.initial_sfen); }catch(e){ local.push(`SFENが不正です: ${e instanceof Error?e.message:e}`); } const bad=[...validateUsiMoves(body.solution_moves),...validateUsiMoves(body.opponent_moves)]; if(bad.length) local.push(`USI形式が不正です: ${bad.join(", ")}`); if(body.solution_moves.length !== (body.mate_length+1)/2) local.push(`solution_moves は ${(body.mate_length+1)/2}手にしてください`); if(body.opponent_moves.length !== Math.floor(body.mate_length/2)) local.push(`opponent_moves は ${Math.floor(body.mate_length/2)}手にしてください`); if(local.length) return local; const remote=await validateProblem(body); return remote.errors; }
  function buildBody(): TsumeProblemInput { return { ...form, initial_sfen: form.initial_sfen.trim(), mate_length:Number(form.mate_length), difficulty:Number(form.difficulty), tags: tagsText.split(/[\n,]/).map(s=>s.trim()).filter(Boolean), solution_moves: parseMoveList(solutionText), opponent_moves: parseMoveList(opponentText) }; }
  function applyRecordedMoves(solution: string[], opponent: string[]) { setSolutionText(solution.join("\n")); setOpponentText(opponent.join("\n")); }
  async function save(){ const body=buildBody(); setMessages([]); setInfo(null); try{ const errs=await runValidation(body); if(errs.length){ setMessages(errs); return; } const saved=editingId ? await updateProblem(editingId, body) : await createProblem(body); setInfo("保存しました"); nav(`/problem-editor/${saved.id}`, { replace:true }); fetchProblems().then(setProblems); }catch(e){ setMessages([`保存に失敗しました: ${e}`]); } }
  async function remove(id:number){ if(!confirm("この問題を削除しますか？")) return; await deleteProblem(id); nav("/problem-editor"); setProblems(ps=>ps.filter(p=>p.id!==id)); }
  return <div className="problem-editor-page"><h1>盤面エディタ・問題作成</h1>{info&&<div className="banner banner-success">{info}</div>}{messages.length>0&&<div className="banner banner-error"><ul>{messages.map(m=><li key={m}>{m}</li>)}</ul></div>}
    <div className="editor-page-layout"><aside className="problem-list"><Link to="/problem-editor" className="home-card">＋ 新規作成</Link>{problems.map(p=><div key={p.id} className={`problem-item ${p.id===editingId?"active":""}`}><Link className="problem-link" to={`/problem-editor/${p.id}`}><span className="problem-title">{p.title}</span><span className="muted">{p.mate_length}手詰</span></Link><button type="button" onClick={()=>remove(p.id)}>削除</button></div>)}</aside>
    <main className="editor-main"><EditorBoard position={pos} onChange={syncSfen}/><div className="form-grid"><label>手番<select value={pos.turn} onChange={e=>syncSfen({...pos, turn:e.target.value as "b"|"w"})}><option value="b">先手</option><option value="w">後手</option></select></label><button type="button" onClick={()=>syncSfen(emptyPosition())}>盤面初期化</button></div>
    <label>SFEN<textarea value={form.initial_sfen || sfen} onChange={e=>setForm({...form, initial_sfen:e.target.value})}/></label><div className="tool-row"><button type="button" onClick={()=>setForm({...form, initial_sfen:sfen})}>現在の局面からSFEN生成</button><button type="button" onClick={applySfen}>SFENを盤面へ反映</button><button type="button" onClick={() => setRecorderSeed((x) => x + 1)}>この局面から手順記録を開始</button></div>
    <div className="form-grid"><label>title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>mate_length<input type="number" step="2" min="1" value={form.mate_length} onChange={e=>setForm({...form,mate_length:Number(e.target.value)})}/></label><label>difficulty<input type="number" min="1" value={form.difficulty} onChange={e=>setForm({...form,difficulty:Number(e.target.value)})}/></label><label><input type="checkbox" checked={form.is_favorite} onChange={e=>setForm({...form,is_favorite:e.target.checked})}/> お気に入り</label></div>
    <SolutionRecorder key={`${form.initial_sfen}-${recorderSeed}`} initialPosition={recorderInitial} onMovesChange={applyRecordedMoves}/><label>tags<textarea value={tagsText} onChange={e=>setTagsText(e.target.value)} placeholder="カンマ区切り、または1行1タグ"/></label><label>solution_moves<textarea value={solutionText} onChange={e=>setSolutionText(e.target.value)} placeholder="例: 5e5d+"/></label><label>opponent_moves<textarea value={opponentText} onChange={e=>setOpponentText(e.target.value)}/></label><label>explanation<textarea value={form.explanation} onChange={e=>setForm({...form,explanation:e.target.value})}/></label><button type="button" className="primary" onClick={save}>検証して保存</button></main></div></div>;
}
